### ISSUE TITLE
Missing the list.txt file for the UrbanCross dataset

### ISSUE THREAD

**Issue by heyuanpengpku** [siruzhong/MM24-UrbanCross#1]
Great work! However, I noticed that the corresponding `list.txt` file for the UrbanCross dataset is missing during loading. Could you kindly share the file? Thank you so much!

**Comment by heyuanpengpku** [comment]
Files like `train_list.txt` and `test_list.txt` seem to be missing as well. I would greatly appreciate it if the authors could provide them. Thank you so much!

**Comment by heyuanpengpku** [comment]
Hello, could you please provide the relevant documents? Thank you very much!

**Comment by siruzhong** [comment]
Sorry for the delayed response and thank you for the question, you can use utils/split_train_test_val.py to generate *_list.txt files.

**Comment by heyuanpengpku** [comment]
Hello, the mentioned Python file does exist, but the required CSV file referenced as `# Load the CSV file containing image captions. df = pd.read_csv(f"{country}/captions.csv")` is not present in the dataset you provided. The only file available is something like `instructblip_generation_spain_refine.csv`. Could you kindly provide further instructions on how to proceed? Thank you!

**Comment by siruzhong** [comment]
You can replace the `df = pd.read_csv(f"{country}/captions.csv")` to `df = pd.read_csv(f"{country}/instructblip_generation_spain_refine.csv")`.  `captions.csv` is the initial version of the text description file for all images, which has some issues. `instructblip_generation_spain_refine.csv` is the final text description file after filtering out the problematic lines.

**Comment by heyuanpengpku** [comment]
Alright, I will make an attempt first. Thank you very much for your timely response!
